/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as CustomizeMarketplacesRouteImport } from './routes/customize.marketplaces'
import { Route as CustomizeInstalledRouteImport } from './routes/customize.installed'
import { Route as CustomizeAgentsRouteImport } from './routes/customize.agents'
import { Route as CustomizeMarketplacesIndexRouteImport } from './routes/customize.marketplaces.index'
import { Route as CustomizeMarketplacesNameRouteImport } from './routes/customize.marketplaces.$name'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as CustomizeMarketplacesNameIndexRouteImport } from './routes/customize.marketplaces.$name.index'
import { Route as CustomizeMarketplacesNamePluginRouteImport } from './routes/customize.marketplaces.$name.$plugin'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const CustomizeMarketplacesRoute = CustomizeMarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => CustomizeRoute,
} as any)
const CustomizeInstalledRoute = CustomizeInstalledRouteImport.update({
  id: '/installed',
  path: '/installed',
  getParentRoute: () => CustomizeRoute,
} as any)
const CustomizeAgentsRoute = CustomizeAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => CustomizeRoute,
} as any)
const CustomizeMarketplacesIndexRoute =
  CustomizeMarketplacesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CustomizeMarketplacesRoute,
  } as any)
const CustomizeMarketplacesNameRoute =
  CustomizeMarketplacesNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => CustomizeMarketplacesRoute,
  } as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const CustomizeMarketplacesNameIndexRoute =
  CustomizeMarketplacesNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CustomizeMarketplacesNameRoute,
  } as any)
const CustomizeMarketplacesNamePluginRoute =
  CustomizeMarketplacesNamePluginRouteImport.update({
    id: '/$plugin',
    path: '/$plugin',
    getParentRoute: () => CustomizeMarketplacesNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/customize': typeof CustomizeRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/customize/agents': typeof CustomizeAgentsRoute
  '/customize/installed': typeof CustomizeInstalledRoute
  '/customize/marketplaces': typeof CustomizeMarketplacesRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/customize/marketplaces/$name': typeof CustomizeMarketplacesNameRouteWithChildren
  '/customize/marketplaces/': typeof CustomizeMarketplacesIndexRoute
  '/customize/marketplaces/$name/$plugin': typeof CustomizeMarketplacesNamePluginRoute
  '/customize/marketplaces/$name/': typeof CustomizeMarketplacesNameIndexRoute
}
export interface FileRoutesByTo {
  '/customize': typeof CustomizeRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/customize/agents': typeof CustomizeAgentsRoute
  '/customize/installed': typeof CustomizeInstalledRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/customize/marketplaces': typeof CustomizeMarketplacesIndexRoute
  '/customize/marketplaces/$name/$plugin': typeof CustomizeMarketplacesNamePluginRoute
  '/customize/marketplaces/$name': typeof CustomizeMarketplacesNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/customize': typeof CustomizeRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/customize/agents': typeof CustomizeAgentsRoute
  '/customize/installed': typeof CustomizeInstalledRoute
  '/customize/marketplaces': typeof CustomizeMarketplacesRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/customize/marketplaces/$name': typeof CustomizeMarketplacesNameRouteWithChildren
  '/customize/marketplaces/': typeof CustomizeMarketplacesIndexRoute
  '/customize/marketplaces/$name/$plugin': typeof CustomizeMarketplacesNamePluginRoute
  '/customize/marketplaces/$name/': typeof CustomizeMarketplacesNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customize'
    | '/pair'
    | '/settings'
    | '/customize/agents'
    | '/customize/installed'
    | '/customize/marketplaces'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/customize/marketplaces/$name'
    | '/customize/marketplaces/'
    | '/customize/marketplaces/$name/$plugin'
    | '/customize/marketplaces/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/customize'
    | '/pair'
    | '/settings'
    | '/customize/agents'
    | '/customize/installed'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/customize/marketplaces'
    | '/customize/marketplaces/$name/$plugin'
    | '/customize/marketplaces/$name'
  id:
    | '__root__'
    | '/_chat'
    | '/customize'
    | '/pair'
    | '/settings'
    | '/customize/agents'
    | '/customize/installed'
    | '/customize/marketplaces'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/general'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/customize/marketplaces/$name'
    | '/customize/marketplaces/'
    | '/customize/marketplaces/$name/$plugin'
    | '/customize/marketplaces/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  CustomizeRoute: typeof CustomizeRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/customize/marketplaces': {
      id: '/customize/marketplaces'
      path: '/marketplaces'
      fullPath: '/customize/marketplaces'
      preLoaderRoute: typeof CustomizeMarketplacesRouteImport
      parentRoute: typeof CustomizeRoute
    }
    '/customize/installed': {
      id: '/customize/installed'
      path: '/installed'
      fullPath: '/customize/installed'
      preLoaderRoute: typeof CustomizeInstalledRouteImport
      parentRoute: typeof CustomizeRoute
    }
    '/customize/agents': {
      id: '/customize/agents'
      path: '/agents'
      fullPath: '/customize/agents'
      preLoaderRoute: typeof CustomizeAgentsRouteImport
      parentRoute: typeof CustomizeRoute
    }
    '/customize/marketplaces/': {
      id: '/customize/marketplaces/'
      path: '/'
      fullPath: '/customize/marketplaces/'
      preLoaderRoute: typeof CustomizeMarketplacesIndexRouteImport
      parentRoute: typeof CustomizeMarketplacesRoute
    }
    '/customize/marketplaces/$name': {
      id: '/customize/marketplaces/$name'
      path: '/$name'
      fullPath: '/customize/marketplaces/$name'
      preLoaderRoute: typeof CustomizeMarketplacesNameRouteImport
      parentRoute: typeof CustomizeMarketplacesRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/customize/marketplaces/$name/': {
      id: '/customize/marketplaces/$name/'
      path: '/'
      fullPath: '/customize/marketplaces/$name/'
      preLoaderRoute: typeof CustomizeMarketplacesNameIndexRouteImport
      parentRoute: typeof CustomizeMarketplacesNameRoute
    }
    '/customize/marketplaces/$name/$plugin': {
      id: '/customize/marketplaces/$name/$plugin'
      path: '/$plugin'
      fullPath: '/customize/marketplaces/$name/$plugin'
      preLoaderRoute: typeof CustomizeMarketplacesNamePluginRouteImport
      parentRoute: typeof CustomizeMarketplacesNameRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface CustomizeMarketplacesNameRouteChildren {
  CustomizeMarketplacesNamePluginRoute: typeof CustomizeMarketplacesNamePluginRoute
  CustomizeMarketplacesNameIndexRoute: typeof CustomizeMarketplacesNameIndexRoute
}

const CustomizeMarketplacesNameRouteChildren: CustomizeMarketplacesNameRouteChildren =
  {
    CustomizeMarketplacesNamePluginRoute: CustomizeMarketplacesNamePluginRoute,
    CustomizeMarketplacesNameIndexRoute: CustomizeMarketplacesNameIndexRoute,
  }

const CustomizeMarketplacesNameRouteWithChildren =
  CustomizeMarketplacesNameRoute._addFileChildren(
    CustomizeMarketplacesNameRouteChildren,
  )

interface CustomizeMarketplacesRouteChildren {
  CustomizeMarketplacesNameRoute: typeof CustomizeMarketplacesNameRouteWithChildren
  CustomizeMarketplacesIndexRoute: typeof CustomizeMarketplacesIndexRoute
}

const CustomizeMarketplacesRouteChildren: CustomizeMarketplacesRouteChildren = {
  CustomizeMarketplacesNameRoute: CustomizeMarketplacesNameRouteWithChildren,
  CustomizeMarketplacesIndexRoute: CustomizeMarketplacesIndexRoute,
}

const CustomizeMarketplacesRouteWithChildren =
  CustomizeMarketplacesRoute._addFileChildren(
    CustomizeMarketplacesRouteChildren,
  )

interface CustomizeRouteChildren {
  CustomizeAgentsRoute: typeof CustomizeAgentsRoute
  CustomizeInstalledRoute: typeof CustomizeInstalledRoute
  CustomizeMarketplacesRoute: typeof CustomizeMarketplacesRouteWithChildren
}

const CustomizeRouteChildren: CustomizeRouteChildren = {
  CustomizeAgentsRoute: CustomizeAgentsRoute,
  CustomizeInstalledRoute: CustomizeInstalledRoute,
  CustomizeMarketplacesRoute: CustomizeMarketplacesRouteWithChildren,
}

const CustomizeRouteWithChildren = CustomizeRoute._addFileChildren(
  CustomizeRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  CustomizeRoute: CustomizeRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
